package com.bongorian.signa1;

import android.app.AlertDialog;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import java.util.*;

final class QualityDialog {
    final MainActivity activity;final CaptureSettings draft;final CameraOptions options;String language=AppLanguage.current();TextView languageField;
    TextView format,size,jpeg,codec,video,bitrate,rawSize,rawRate,rawInfo;Switch rawMode;LinearLayout content;
    QualityDialog(MainActivity a){activity=a;draft=new CaptureSettings(a.settings);options=a.cameraOptions;}
    void heading(String label){TextView t=activity.text(label,13,MainActivity.LIME);t.setTypeface(null,Typeface.BOLD);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,activity.dp(32));p.topMargin=activity.dp(8);content.addView(t,p);}
    TextView field(){TextView t=activity.text("",13,MainActivity.WHITE);t.setPadding(activity.dp(12),activity.dp(8),activity.dp(12),activity.dp(8));t.setBackground(activity.bg(MainActivity.PANEL,12,0));t.setMinHeight(activity.dp(62));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=activity.dp(7);content.addView(t,p);return t;}
    void pick(String title,String[] labels,int selected,java.util.function.IntConsumer chosen){
        LinearLayout list=new LinearLayout(activity);list.setOrientation(LinearLayout.VERTICAL);int[] draftIndex={Math.max(0,selected)};TextView[] rows=new TextView[labels.length];
        Runnable refreshSelection=()->{for(int n=0;n<rows.length;n++){rows[n].setText((n==draftIndex[0]?"✓  ":"    ")+labels[n]);rows[n].setTextColor(n==draftIndex[0]?MainActivity.LIME:MainActivity.WHITE);rows[n].setBackground(activity.bg(MainActivity.PANEL,14,n==draftIndex[0]?0x665F7940:0));}};
        for(int n=0;n<labels.length;n++){final int index=n;TextView row=activity.text("",13,MainActivity.WHITE);row.setPadding(activity.dp(12),activity.dp(12),activity.dp(12),activity.dp(12));rows[n]=row;LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=activity.dp(8);row.setMinHeight(activity.dp(56));list.addView(row,lp);row.setOnClickListener(v->{draftIndex[0]=index;refreshSelection.run();});}
        refreshSelection.run();SignalSheet.show(activity,title,activity.getString(R.string.ui_select_an_option_then_apply),list,()->{if(labels.length>0){chosen.accept(draftIndex[0]);refresh();}});
    }

    void show(){ScrollView scroll=new ScrollView(activity);content=new LinearLayout(activity);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(activity.dp(16),0,activity.dp(16),activity.dp(12));content.setBackgroundColor(MainActivity.BG);scroll.addView(content);
        heading(activity.getString(R.string.language_title));languageField=field();languageField.setOnClickListener(v->pick(activity.getString(R.string.language_title),AppLanguage.labels(activity),AppLanguage.index(language),n->language=AppLanguage.TAGS[n]));
        if(options==null){content.addView(activity.text(activity.getString(R.string.camera_settings_unavailable),13,MainActivity.MUTED));refresh();scroll.removeView(content);SignalSheet.show(activity,activity.getString(R.string.ui_settings),activity.getString(R.string.language_title),content,()->AppLanguage.select(language));return;}
        heading(activity.getString(R.string.ui_photo_full_resolution));format=field();format.setOnClickListener(v->{String[] labels=options.raws.isEmpty()?new String[]{activity.getString(R.string.ui_processed_jpeg)}:new String[]{activity.getString(R.string.ui_processed_jpeg),activity.getString(R.string.ui_raw_dng_original),activity.getString(R.string.ui_raw_dng_sensor_processing)};pick(activity.getString(R.string.ui_save_format),labels,draft.photoFormat,n->{draft.photoFormat=n;draft.photoSize="auto";});});
        size=field();size.setOnClickListener(v->{List<CameraOptions.Photo> choices=draft.photoFormat==0?options.photos:options.raws;String[] labels=new String[choices.size()+2];labels[0]=activity.getString(R.string.ui_standard_prefer_12_mp_or_less);labels[1]=activity.getString(R.string.ui_maximum_camera_resolution);int selected="max".equals(draft.photoSize)?1:0;for(int i=0;i<choices.size();i++){labels[i+2]=choices.get(i).label(activity);if(choices.get(i).key().equals(draft.photoSize))selected=i+2;}pick(activity.getString(R.string.ui_photo_resolution),labels,selected,n->draft.photoSize=n==0?"auto":n==1?"max":choices.get(n-2).key());});
        jpeg=field();jpeg.setOnClickListener(v->{if(draft.photoFormat!=0)return;int[] qualities={85,95,100};int selected=draft.jpegQuality==85?0:draft.jpegQuality==100?2:1;pick(activity.getString(R.string.ui_jpeg_quality),new String[]{activity.getString(R.string.ui_85_smaller_files),activity.getString(R.string.ui_95_high_quality),activity.getString(R.string.ui_100_best_quality)},selected,n->draft.jpegQuality=qualities[n]);});
        heading(activity.getString(R.string.ui_video_resolution_and_frame_rate));
        rawMode=new Switch(activity);rawMode.setText(activity.getString(R.string.ui_raw_video_dng_sequence_experimental));rawMode.setTextColor(MainActivity.WHITE);rawMode.setChecked(draft.rawVideo&&options.rawVideoAvailable());rawMode.setEnabled(options.rawVideoAvailable());content.addView(rawMode,new LinearLayout.LayoutParams(-1,activity.dp(48)));
        rawMode.setOnCheckedChangeListener((button,checked)->{draft.rawVideo=checked;refresh();});
        rawInfo=activity.text(options.rawVideoReason(activity)+activity.getString(R.string.ui_saves_original_silent_dng_frames_as_a_zip),11,MainActivity.MUTED);content.addView(rawInfo);
        rawSize=field();rawSize.setOnClickListener(v->{String[] labels=options.rawVideos.stream().map(item->item.label(activity)).toArray(String[]::new);int selected=0;for(int n=0;n<options.rawVideos.size();n++)if(options.rawVideos.get(n)==options.rawVideo(draft))selected=n;pick(activity.getString(R.string.ui_raw_video_resolution),labels,selected,n->draft.rawVideoSize=options.rawVideos.get(n).size.toString());});
        rawRate=field();rawRate.setOnClickListener(v->{CameraOptions.RawVideo choice=options.rawVideo(draft);if(choice==null)return;String[] labels=new String[choice.maxFps];for(int n=1;n<=choice.maxFps;n++)labels[n-1]=n+activity.getString(R.string.ui_fps_target);pick(activity.getString(R.string.ui_raw_video_target_frame_rate),labels,Math.min(draft.rawVideoFps,choice.maxFps)-1,n->draft.rawVideoFps=n+1);});
        codec=field();codec.setOnClickListener(v->{List<String> keys=new ArrayList<>(),labels=new ArrayList<>();for(String key:new String[]{"video/hevc","video/avc"})if(!options.videosFor(key).isEmpty()){keys.add(key);labels.add(key.equals("video/hevc")?activity.getString(R.string.ui_hevc_h_265_efficient):activity.getString(R.string.ui_avc_h_264_compatible));}pick(activity.getString(R.string.ui_video_codec),labels.toArray(new String[0]),keys.indexOf(draft.codec),n->{draft.codec=keys.get(n);draft.videoKey="";});});
        video=field();video.setOnClickListener(v->{List<CameraOptions.Video> choices=options.videosFor(draft.codec);String[] labels=new String[choices.size()];int selected=0;for(int i=0;i<choices.size();i++){labels[i]=choices.get(i).label(activity);if(choices.get(i).key().equals(options.video(draft).key()))selected=i;}pick(activity.getString(R.string.ui_video_resolution_fps),labels,selected,n->draft.videoKey=choices.get(n).key());});
        bitrate=field();bitrate.setOnClickListener(v->{String[] names={activity.getString(R.string.ui_smaller_files),activity.getString(R.string.ui_high_quality),activity.getString(R.string.ui_best_quality),activity.getString(R.string.ui_encoder_maximum)};String[] labels=new String[4];for(int i=0;i<4;i++){CaptureSettings s=new CaptureSettings(draft);s.videoQuality=i;int rate=options.bitrate(options.video(s),s);labels[i]=names[i]+String.format(Locale.US,activity.getString(R.string.ui_1f_mbps_approx_0f_mb_min),rate/1e6,rate*60/8e6);}pick(activity.getString(R.string.ui_video_quality),labels,draft.videoQuality,n->draft.videoQuality=n);});
        heading(activity.getString(R.string.ui_location_and_exif));Switch gps=new Switch(activity);gps.setText(activity.getString(R.string.ui_save_capture_location));gps.setTextColor(MainActivity.WHITE);gps.setChecked(draft.location);gps.setOnCheckedChangeListener((b,checked)->draft.location=checked);content.addView(gps,new LinearLayout.LayoutParams(-1,activity.dp(48)));
        TextView note=activity.text(activity.getString(R.string.ui_photos_include_the_date_device_exposure_iso_and),11,MainActivity.MUTED);note.setPadding(0,activity.dp(12),0,activity.dp(8));note.setLineSpacing(activity.dp(3),1);content.addView(note);
        TextView privacy=field();privacy.setText(BuildConfig.APP_NAME+" "+BuildConfig.VERSION_NAME+"\n"+activity.getString(R.string.ui_privacy_policy_support));privacy.setOnClickListener(v->AboutDialog.show(activity));
        refresh();scroll.removeView(content);SignalSheet.show(activity,activity.getString(R.string.ui_capture_settings),activity.getString(R.string.ui_resolution_format_and_location),content,()->{activity.applySettings(draft);AppLanguage.select(language);});
    }
    void refresh(){
        languageField.setText(activity.getString(R.string.language_summary)+"\n"+AppLanguage.labels(activity)[AppLanguage.index(language)]);if(options==null)return;
        CameraOptions.RawVideo raw=options.rawVideo(draft);boolean active=draft.rawVideo&&options.rawVideoAvailable();rawSize.setVisibility(active?View.VISIBLE:View.GONE);rawRate.setVisibility(active?View.VISIBLE:View.GONE);rawSize.setEnabled(active);rawRate.setEnabled(active);
        if(raw!=null){int fps=Math.min(draft.rawVideoFps,raw.maxFps);rawSize.setText(activity.getString(R.string.ui_raw_video_resolution_39)+raw.label(activity));rawRate.setText(String.format(Locale.US,activity.getString(R.string.ui_raw_video_target_frame_rate_d_fps_approx),fps,CameraOptions.area(raw.size)*2*fps/1e6));}
        CameraOptions.Photo p=options.photo(draft);CameraOptions.Video v=options.video(draft);format.setText(activity.getString(R.string.ui_photo_format)+(draft.photoFormat==0?activity.getString(R.string.ui_processed_jpeg):draft.photoFormat==1?activity.getString(R.string.ui_raw_dng_original):activity.getString(R.string.ui_raw_dng_sensor_processing)));size.setText(activity.getString(R.string.ui_photo_resolution_42)+(p==null?activity.getString(R.string.ui_unavailable_on_this_camera):p.label(activity)));jpeg.setText(draft.photoFormat==0?activity.getString(R.string.ui_jpeg_quality_44)+draft.jpegQuality+" / 100":activity.getString(R.string.ui_raw_quality_uncompressed_sensor_data));jpeg.setAlpha(draft.photoFormat==0?1:.55f);codec.setText(activity.getString(R.string.ui_video_codec_46)+(draft.codec.equals("video/hevc")?"HEVC / H.265":"AVC / H.264"));video.setText(activity.getString(R.string.ui_video_resolution_fps_47)+(v==null?activity.getString(R.string.ui_unavailable):v.label(activity)));codec.setEnabled(v!=null&&!active);video.setEnabled(v!=null&&!active);bitrate.setEnabled(v!=null&&!active);for(TextView field:new TextView[]{codec,video,bitrate})field.setAlpha(active?.35f:1);int rate=v==null?0:options.bitrate(v,draft);bitrate.setText(String.format(Locale.US,activity.getString(R.string.ui_video_quality_1f_mbps_approx_0f_mb_min),rate/1e6,rate*60/8e6));}
}
