package com.bongorian.signa1;

import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import java.util.*;

final class QualityDialog {
    final MainActivity activity;final CaptureSettings draft;final CameraOptions options;boolean advanced;String language=AppLanguage.current();TextView languageField,loadNote;
    android.app.Dialog sheet;
    TextView format,size,jpeg,codec,video,bitrate,rawSize,rawRate,rawInfo;SignalToggle rawMode;LinearLayout content;
    QualityDialog(MainActivity a){activity=a;advanced=a.advancedMode;draft=new CaptureSettings(a.settings);options=a.cameraOptions;}
    void heading(String label){TextView t=activity.text(label,13,MainActivity.LIME);activity.typography(t,MainActivity.TEXT_LABEL,true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,activity.dp(32));p.topMargin=content.getChildCount()==0?0:activity.dp(20);p.bottomMargin=activity.dp(6);content.addView(t,p);}
    TextView field(){TextView t=activity.text("",MainActivity.TEXT_LABEL,MainActivity.WHITE);t.setPadding(activity.dp(12),activity.dp(8),activity.dp(12),activity.dp(8));t.setBackground(activity.bg(MainActivity.PANEL,0));t.setMinHeight(activity.dp(56));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=activity.dp(7);content.addView(t,p);return t;}
    void pick(String title,String[] labels,int selected,java.util.function.IntConsumer chosen){
        SignalSheet.pick(activity,title,labels,selected,n->{chosen.accept(n);refresh();});
    }

    void show(){ScrollView scroll=new ScrollView(activity);content=new LinearLayout(activity);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,0,0,activity.dp(8));content.setBackgroundColor(MainActivity.BG);scroll.addView(content);
        heading(activity.getString(R.string.settings_modes));
        mode(R.string.ui_advanced_mode,R.string.ui_advanced_settings_hint,advanced,"advanced-mode",checked->advanced=checked);
        mode(R.string.expert_mode,R.string.expert_hint,draft.expertMode,"expert-mode",checked->{draft.expertMode=checked;refresh();});
        if(options==null){note(activity.getString(R.string.camera_settings_unavailable));appSection();refresh();scroll.removeView(content);sheet=SignalSheet.show(activity,activity.getString(R.string.ui_settings),activity.getString(R.string.settings_summary),content,this::apply);return;}
        heading(activity.getString(R.string.load_title));loadNote=note("");TextView recommend=field();recommend.setTag("load-recommend");recommend.setText(activity.getString(R.string.load_use_recommended));recommend.setOnClickListener(v->{draft.photoSize="recommended";draft.videoKey="recommended";draft.videoQuality=1;refresh();});
        heading(activity.getString(R.string.settings_photo));note(activity.getString(R.string.fault_signal_photo_note));format=field();format.setOnClickListener(v->{String[] labels=options.raws.isEmpty()?new String[]{activity.getString(R.string.ui_processed_jpeg)}:new String[]{activity.getString(R.string.ui_processed_jpeg),activity.getString(R.string.ui_raw_dng_sensor_processing)};pick(activity.getString(R.string.ui_save_format),labels,draft.photoFormat==0?0:1,n->{draft.photoFormat=n==0?0:2;draft.photoSize="recommended";});});
        size=field();size.setOnClickListener(v->{List<CameraOptions.Photo> choices=draft.photoFormat==0?options.photos:options.raws;String[] labels=new String[choices.size()+3];labels[0]=activity.getString(R.string.load_recommended);labels[1]=activity.getString(draft.photoFormat==0?R.string.fault_live_resolution:R.string.ui_standard_prefer_12_mp_or_less);labels[2]=activity.getString(draft.photoFormat==0?R.string.fault_live_max:R.string.ui_maximum_camera_resolution);int selected="max".equals(draft.photoSize)?2:"auto".equals(draft.photoSize)?1:0;for(int i=0;i<choices.size();i++){labels[i+3]=choices.get(i).label(activity);if(choices.get(i).key().equals(draft.photoSize))selected=i+3;}pick(activity.getString(R.string.ui_photo_resolution),labels,selected,n->draft.photoSize=n==0?"recommended":n==1?"auto":n==2?"max":choices.get(n-3).key());});
        jpeg=field();jpeg.setOnClickListener(v->{if(draft.photoFormat!=0)return;int[] qualities={85,95,100};int selected=draft.jpegQuality==85?0:draft.jpegQuality==100?2:1;pick(activity.getString(R.string.ui_jpeg_quality),new String[]{activity.getString(R.string.ui_85_smaller_files),activity.getString(R.string.ui_95_high_quality),activity.getString(R.string.ui_100_best_quality)},selected,n->draft.jpegQuality=qualities[n]);});
        heading(activity.getString(R.string.settings_video));
        codec=field();codec.setOnClickListener(v->{List<String> keys=new ArrayList<>(),labels=new ArrayList<>();for(String key:new String[]{"video/hevc","video/avc"})if(!options.videosFor(key).isEmpty()){keys.add(key);labels.add(key.equals("video/hevc")?activity.getString(R.string.ui_hevc_h_265_efficient):activity.getString(R.string.ui_avc_h_264_compatible));}pick(activity.getString(R.string.ui_video_codec),labels.toArray(new String[0]),keys.indexOf(draft.codec),n->{draft.codec=keys.get(n);draft.videoKey="";});});
        video=field();video.setOnClickListener(v->{List<CameraOptions.Video> choices=options.videosFor(draft.codec);String[] labels=new String[choices.size()+1];labels[0]=activity.getString(R.string.load_recommended);int selected=0;for(int i=0;i<choices.size();i++){labels[i+1]=choices.get(i).label(activity);if(choices.get(i).key().equals(draft.videoKey))selected=i+1;}pick(activity.getString(R.string.ui_video_resolution_fps),labels,selected,n->draft.videoKey=n==0?"recommended":choices.get(n-1).key());});
        bitrate=field();bitrate.setOnClickListener(v->{String[] names={activity.getString(R.string.ui_smaller_files),activity.getString(R.string.ui_high_quality),activity.getString(R.string.ui_best_quality),activity.getString(R.string.ui_encoder_maximum)};String[] labels=new String[4];for(int i=0;i<4;i++){CaptureSettings s=new CaptureSettings(draft);s.videoQuality=i;int rate=options.bitrate(options.video(s),s);labels[i]=names[i]+String.format(Locale.US,activity.getString(R.string.ui_1f_mbps_approx_0f_mb_min),rate/1e6,rate*60/8e6);}pick(activity.getString(R.string.ui_video_quality),labels,draft.videoQuality,n->draft.videoQuality=n);});
        heading(activity.getString(R.string.settings_raw_video));
        rawMode=new SignalToggle(activity,activity.getString(R.string.settings_raw_enable),draft.rawVideo&&options.rawVideoAvailable());rawMode.setEnabled(options.rawVideoAvailable());content.addView(rawMode,new LinearLayout.LayoutParams(-1,activity.dp(48)));
        rawMode.setOnCheckedChangeListener((button,checked)->{draft.rawVideo=checked;refresh();});
        rawInfo=note(options.rawVideoReason(activity)+activity.getString(R.string.ui_saves_original_silent_dng_frames_as_a_zip));
        rawSize=field();rawSize.setOnClickListener(v->{String[] labels=options.rawVideos.stream().map(item->item.label(activity)).toArray(String[]::new);int selected=0;for(int n=0;n<options.rawVideos.size();n++)if(options.rawVideos.get(n)==options.rawVideo(draft))selected=n;pick(activity.getString(R.string.ui_raw_video_resolution),labels,selected,n->draft.rawVideoSize=options.rawVideos.get(n).size.toString());});
        rawRate=field();rawRate.setOnClickListener(v->{CameraOptions.RawVideo choice=options.rawVideo(draft);if(choice==null)return;String[] labels=new String[choice.maxFps];for(int n=1;n<=choice.maxFps;n++)labels[n-1]=n+activity.getString(R.string.ui_fps_target);pick(activity.getString(R.string.ui_raw_video_target_frame_rate),labels,Math.min(draft.rawVideoFps,choice.maxFps)-1,n->draft.rawVideoFps=n+1);});
        heading(activity.getString(R.string.settings_metadata));SignalToggle gps=new SignalToggle(activity,activity.getString(R.string.ui_save_capture_location),draft.location);gps.setOnCheckedChangeListener((b,checked)->draft.location=checked);content.addView(gps,new LinearLayout.LayoutParams(-1,activity.dp(48)));
        note(activity.getString(R.string.settings_metadata_hint));
        appSection();refresh();scroll.removeView(content);sheet=SignalSheet.show(activity,activity.getString(R.string.ui_settings),activity.getString(R.string.settings_summary),content,this::apply);
    }
    TextView note(String label){TextView note=activity.text(label,MainActivity.TEXT_BODY,MainActivity.MUTED);note.setLineSpacing(activity.dp(3),1);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=activity.dp(5);p.bottomMargin=activity.dp(12);content.addView(note,p);return note;}
    void mode(int label,int hint,boolean value,String tag,java.util.function.Consumer<Boolean> changed){SignalToggle toggle=new SignalToggle(activity,activity.getString(label),value);toggle.setTag(tag);content.addView(toggle,new LinearLayout.LayoutParams(-1,activity.dp(48)));note(activity.getString(hint));toggle.setOnCheckedChangeListener((view,checked)->changed.accept(checked));}
    void appSection(){heading(activity.getString(R.string.settings_app));TextView tutorial=field();tutorial.setTag("settings-tutorial");tutorial.setText(activity.getString(R.string.tutorial_title));tutorial.setOnClickListener(v->activity.showTutorial());languageField=field();languageField.setOnClickListener(v->pick(activity.getString(R.string.language_title),AppLanguage.labels(activity),AppLanguage.index(language),n->language=AppLanguage.TAGS[n]));TextView privacy=field();privacy.setText(BuildConfig.APP_NAME+" "+BuildConfig.VERSION_NAME+"\n"+activity.getString(R.string.ui_privacy_policy_support));privacy.setOnClickListener(v->AboutDialog.show(activity));}
    void apply(){saveAdvanced();activity.applySettings(draft);AppLanguage.select(language);}
    void saveAdvanced(){activity.advancedMode=advanced;activity.getSharedPreferences("signal",0).edit().putBoolean("advancedMode",advanced).apply();}
    void refresh(){
        if(loadNote!=null)loadNote.setText(activity.getString(draft.expertMode?R.string.expert_load_hint:R.string.load_hint));if(languageField!=null)languageField.setText(activity.getString(R.string.language_summary)+"\n"+AppLanguage.labels(activity)[AppLanguage.index(language)]);if(options==null)return;
        CameraOptions.RawVideo raw=options.rawVideo(draft);boolean active=draft.rawVideo&&options.rawVideoAvailable();rawInfo.setVisibility(active||!options.rawVideoAvailable()?View.VISIBLE:View.GONE);rawSize.setVisibility(active?View.VISIBLE:View.GONE);rawRate.setVisibility(active?View.VISIBLE:View.GONE);rawSize.setEnabled(active);rawRate.setEnabled(active);
        if(raw!=null){int fps=Math.min(draft.rawVideoFps,raw.maxFps);rawSize.setText(activity.getString(R.string.ui_raw_video_resolution_39)+raw.label(activity));rawRate.setText(String.format(Locale.US,activity.getString(R.string.ui_raw_video_target_frame_rate_d_fps_approx),fps,CameraOptions.area(raw.size)*2*fps/1e6));}
        CameraOptions.Photo p=options.photo(draft);CameraOptions.Video v=options.video(draft);format.setText(activity.getString(R.string.ui_photo_format)+(draft.photoFormat==0?activity.getString(R.string.ui_processed_jpeg):activity.getString(R.string.ui_raw_dng_sensor_processing)));size.setText(activity.getString(R.string.ui_photo_resolution_42)+("recommended".equals(draft.photoSize)?activity.getString(R.string.load_auto_prefix):"")+(p==null?activity.getString(R.string.ui_unavailable_on_this_camera):p.label(activity)));jpeg.setText(draft.photoFormat==0?activity.getString(R.string.ui_jpeg_quality_44)+draft.jpegQuality+" / 100":activity.getString(R.string.ui_raw_quality_uncompressed_sensor_data));jpeg.setAlpha(draft.photoFormat==0?1:.55f);codec.setText(activity.getString(R.string.ui_video_codec_46)+(draft.codec.equals("video/hevc")?"HEVC / H.265":"AVC / H.264"));video.setText(activity.getString(R.string.ui_video_resolution_fps_47)+("recommended".equals(draft.videoKey)?activity.getString(R.string.load_auto_prefix):"")+(v==null?activity.getString(R.string.ui_unavailable):v.label(activity)));codec.setEnabled(v!=null&&!active);video.setEnabled(v!=null&&!active);bitrate.setEnabled(v!=null&&!active);for(TextView field:new TextView[]{codec,video,bitrate})field.setAlpha(active?.35f:1);int rate=v==null?0:options.bitrate(v,draft);bitrate.setText(String.format(Locale.US,activity.getString(R.string.ui_video_quality_1f_mbps_approx_0f_mb_min),rate/1e6,rate*60/8e6));}
}
